### ISSUE TITLE
🐛 Bug: Deserialization Error on Minio plugin - fresh upstall

### ISSUE THREAD

**Issue by jpbourgeon** [nocodb/nocodb#10332]
### Please confirm that the bug report does ***not*** already exist

- [x] I confirm there is no existing issue for this bug.

### Steps to reproduce

I can't make minio work on my instance behind an nginx reverse-proxy.

Nocodb works fine but the Minio plugin throws :
```
{
    "msg": "char '4' is not expected.:1:1\n  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object."
}
```

Nocodb is installed with the upstall script : subdomain for nocodb and minio (nocodb-s3), both without a certificate. Nginx handles the certificates.

@DarkPhoenix2704 may I ask for your assistance ?

### Desired Behavior

Nocodb should be able to talk to a minio storage instance through a reverse-proxy gracefully.

### Project Details

Node: **v22.13.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.260.2**

**Comment by jpbourgeon** [comment]
I installed with the upstall script, changed the URLs in docker.env and started/stopped the stack manually with docker-compose commands.

docker.env :
```shell
POSTGRES_DB=nocodb
POSTGRES_USER=postgres
POSTGRES_PASSWORD=*****
NC_DB=pg://db:5432?d=nocodb&user=postgres&password=*****
REDIS_PASSWORD=*****
NC_REDIS_URL=redis://:*****@redis:6379/0
MINIO_ROOT_USER=*****
MINIO_ROOT_PASSWORD=*****
NC_S3_BUCKET_NAME=nocodb
NC_S3_REGION=us-east-1
NC_S3_ACCESS_KEY=*****
NC_S3_ACCESS_SECRET=*****
NC_S3_FORCE_PATH_STYLE=true
NC_S3_ENDPOINT=https://nocodb-s3.cdg71.fr
NC_PUBLIC_URL=https://nocodb.cdg71.fr
```
docker-compose.yml
```yaml
services:
  nocodb:
    image: nocodb/nocodb:latest
    env_file: docker.env
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - db
      - redis
      - minio
    restart: unless-stopped
    volumes:
      - ./nocodb:/usr/app/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.nocodb.rule=Host(`nocodb.cdg71.fr`)"
      - "traefik.http.routers.nocodb.entrypoints=web"
    networks:
      - nocodb-network
  db:
    image: postgres:16.6
    env_file: docker.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nocodb-network
  traefik:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.minio.address=:9000"
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    depends_on:
      - nocodb
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - nocodb-network

  redis:
    image: redis:latest
    restart: unless-stopped
    env_file: docker.env
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD}"
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$${REDIS_PASSWORD}", "--raw", "incr", "ping" ]
    volumes:
      - ./redis:/data
    networks:
      - nocodb-network
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    env_file: docker.env
    entrypoint: /bin/sh
    volumes:
      - ./minio:/export
    command: -c 'mkdir -p /export/nocodb && /usr/bin/minio server /export'
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio.rule=Host(`nocodb-s3.cdg71.fr`)"
      - "traefik.http.routers.minio.entrypoints=web"
    networks:
      - nocodb-network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 2 * * 6" --cleanup
    restart: unless-stopped
    networks:
      - nocodb-network

volumes:
    redis:
networks:
  nocodb-network:
    driver: bridge
```

**Comment by jpbourgeon** [comment]
Finally, here is my nginx config file

NocoDB (nocodb) :
```nginx
# websocket upstream config
upstream nocodb_ws {
  server 10.10.1.20;
}

server {
  server_name nocodb.cdg71.fr;

  include /etc/nginx/snippets/config-commune.conf;
  include /etc/nginx/snippets/no-robot.conf;

  # Allow special characters in headers
  ignore_invalid_headers off;
  # Disable buffering
  proxy_buffering off;
  proxy_request_buffering off;
  chunked_transfer_encoding off;

  location / {
    # return 503; # mode maintenance
    proxy_pass http://nocodb_ws;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Websocket support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_connect_timeout 300;
    proxy_read_timeout 300;
    proxy_send_timeout 300;
  }

  error_page 503 @maintenance;
  location @maintenance {
    root /var/www/html;
    rewrite ^(.*)$ /503.html break;
  }

  listen 443 ssl; # managed by Certbot
  ssl_certificate /etc/letsencrypt/live/nocodb.cdg71.fr/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/nocodb.cdg71.fr/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
  if ($host = nocodb.cdg71.fr) {
    return 301 https://$host$request_uri;
  } # managed by Certbot


  server_name nocodb.cdg71.fr;
  listen 80;
  return 404; # managed by Certbot

}
```

Minio (nocodb-s3) :
```nginx
# websocket upstream config
upstream nocodb-s3_ws {
  server 10.10.1.20:9000;
}

server {
  server_name nocodb-s3.cdg71.fr;

  include /etc/nginx/snippets/config-commune.conf;
  include /etc/nginx/snippets/no-robot.conf;

  # Allow special characters in headers
  ignore_invalid_headers off;
  # Disable buffering
  proxy_buffering off;
  proxy_request_buffering off;
  chunked_transfer_encoding off;

  location / {
    # return 503; # mode maintenance
    proxy_pass http://nocodb-s3_ws;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Websocket support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_connect_timeout 300;
    proxy_read_timeout 300;
    proxy_send_timeout 300;
  }

  error_page 503 @maintenance;
  location @maintenance {
    root /var/www/html;
    rewrite ^(.*)$ /503.html break;
  }

  listen 443 ssl; # managed by Certbot
  ssl_certificate /etc/letsencrypt/live/nocodb-s3.cdg71.fr/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/nocodb-s3.cdg71.fr/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
  if ($host = nocodb-s3.cdg71.fr) {
    return 301 https://$host$request_uri;
  } # managed by Certbot


  server_name nocodb-s3.cdg71.fr;
  listen 80;
  return 404; # managed by Certbot

}
```

**Comment by jpbourgeon** [comment]
I decided to rewrite the whole stack to bypass traefik altogether.

**Comment by ThrillKickerMatt** [comment]
@jpbourgeon I have the same error and same requirements as you. Using nocodb with Nginx as a reverse proxy and getting the same error. Do you indeed think it is traefik? Can you maybe provide more details of you how got it working?

**Comment by jpbourgeon** [comment]
Hi @ThrillKickerMatt

Simply put I stopped troubleshooting and wrote my own docker compose
deployment stack.

I published it here for reference :
https://github.com/cdg71/nocodb-onprem-deploy

Feel free to reuse it !


Le mer. 13 août 2025, 17:03, ThrillKicker-Matt ***@***.***> a
écrit :

**Comment by ThrillKickerMatt** [comment]
Thank you! I will give it a try.

**Comment by ThrillKickerMatt** [comment]
I am running into an issue now where the nocodb container keeps rebooting. 

Error: getaddrinfo EAI_AGAIN db

I had to use another port in the docker-compose.yml file since I am using port 80. Everything else is up and running. I have also set up the Nginx configuration, if that matters at this point.

**Comment by jpbourgeon** [comment]
Congrats! Docker Compose setups are always context-dependent and can be
picky to get right!


Le mer. 13 août 2025, 21:48, ThrillKicker-Matt ***@***.***> a
écrit :

**Comment by ThrillKickerMatt** [comment]
I am still having an issue with the nocodb container in a constant boot loop. Everything else is up including MinIO and the others. The full error is below.

Error: getaddrinfo EAI_AGAIN db     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:122:26) {   errno: -3001,   code: 'EAI_AGAIN',   syscall: 'getaddrinfo',   hostname: 'db' }

I've tried to install on another VM and got the same issue.

**Comment by jpbourgeon** [comment]
that getaddrinfo EAI_AGAIN db means NocoDB can’t resolve the hostname db
from inside its container. That’s almost always one of these:

there’s no service actually named db in your compose

NocoDB and your DB aren’t on the same Docker network

the DB isn’t healthy yet and NocoDB tries too early

the DB host env var points to db, but your service has another name


Changing the host port (because 80 is busy) won’t affect
container-to-container DNS. Inside the compose network, services reach each
other by service name (e.g. db:5432), not by host ports like localhost:5432.

Quick checks

Run these to confirm what’s wrong:
```
# Show services and state
docker compose ps

# See logs from both containers
docker compose logs -f db nocodb

# From inside NocoDB, resolve the db hostname
docker compose exec nocodb getent hosts db || true

# Inspect the default network to verify both services are attached
docker network ls
docker network inspect <yourproject>_default
```

If getent hosts db returns nothing, DNS can’t find db (name mismatch or
network). If it resolves but NocoDB still fails, the DB likely isn’t ready
yet.


Le jeu. 14 août 2025, 14:43, ThrillKicker-Matt ***@***.***> a
écrit :

**Comment by ThrillKickerMatt** [comment]
Right, but the only thing that was changed in my docker-compose.yml file was the port. Why would anything be looking for the service 'db'?

I will check these things and update shortly.

**Comment by ThrillKickerMatt** [comment]
The logs command returned what I gave above for the nocodb, but nothing for db since it is not a container. The other command that returned information was the network, but there was nothing usable there just the names. I did remove a few unused ones thinking there was a conflict but I am still getting the reboot.

Most of the commands either returned nothing or gave an error. The getent hosts command tells me that since the nocodb container is not up, it cannot return anything. 

Again, the ONLY thing I changed from your git was the port from 80 to another unused port.

**Comment by ThrillKickerMatt** [comment]
I wiped everything and started fresh. I found this in the logs.

minio_1           | Added `myminio` successfully.
minio_1           | Creating bucket 'nocodb'...
postgres_1        | 2025-08-14 18:42:13.832 UTC [1] LOG:  starting PostgreSQL 16.6 (Debian 16.6-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres_1        | 2025-08-14 18:42:13.834 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1        | 2025-08-14 18:42:13.834 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1        | 2025-08-14 18:42:13.848 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1        | 2025-08-14 18:42:13.911 UTC [72] LOG:  database system was shut down at 2025-08-14 18:42:13 UTC
postgres_1        | 2025-08-14 18:42:13.973 UTC [1] LOG:  database system is ready to accept connections
minio_1           | Bucket created successfully `myminio/nocodb`.
minio_1           | Bucket 'nocodb' created successfully.
nocodb_1          | ╔══════════════════════════════════════════════════════════════════════════════╗║                                                                              ║║   EXCEPTION OCCURED!! in PGClient @ createDatabaseIfNotExists                ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   MESSAGE:                                                                   ║║   getaddrinfo EAI_AGAIN db                                                   ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   CODE:                                                                      ║║   EAI_AGAIN                                                                  ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   STACK:                                                                     ║║   Error: getaddrinfo EAI_AGAIN db                                            ║║   at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:122:26)        ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║                                                                              ║║                                                                              ║╚══════════════════════════════════════════════════════════════════════════════╝
nocodb_1          | Error: getaddrinfo EAI_AGAIN db
nocodb_1          |     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:122:26) {
nocodb_1          |   errno: -3001,
nocodb_1          |   code: 'EAI_AGAIN',
nocodb_1          |   syscall: 'getaddrinfo',
nocodb_1          |   hostname: 'db'
nocodb_1          | }


Is nocodb looking for the bucket called 'db' and minio created the bucket called 'nocodb'? Or is 'db' something else?
