### ISSUE TITLE
Missing filtering logic in M2M

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#337]
**Please enter the following details**
"Search Records" field not working at all

**Steps To Reproduce**
1. Create a M2M column
2. Click '+' to add a record
3. Type a primary name (e.g. Australia) in Search records
4. The list of record remains unchanged

**Expected behavior**
After specifying the target primary name, the list should be updated if the record is found or it should show a message like "record not found" 

**Screenshots**
![image](https://user-images.githubusercontent.com/35857179/125293965-7d12aa80-e356-11eb-8e08-dd3cfdcd929a.png)

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.10.1**

**Comment by pranavxc** [comment]
Fixed in `v0.10.2`

**Comment by wingkwong** [comment]
@pranavxc It's not working again. 

![image](https://user-images.githubusercontent.com/35857179/144531054-e9d47fa9-7b71-4ffd-b6cf-e8c900759617.png)

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.83.5**

**Comment by pranavxc** [comment]
> @pranavxc It's not working again.
> 
> ![image](https://user-images.githubusercontent.com/35857179/144531054-e9d47fa9-7b71-4ffd-b6cf-e8c900759617.png)
> 
> Node: **v12.22.6** Arch: **x64** Platform: **linux** Docker: **false** Database: **pg** ProjectOnRootDB: **false** RootDB: **pg** PackageVersion: **0.83.5**

the filter will happen only after enter key press, if still fails please reply here.

**Comment by wingkwong** [comment]
@pranavxc I tried entering key press / clicking the "Apply filter" button. It still fails.

**Comment by o1lab** [comment]
This appears to work in REST API projects and fail only in GraphQL

**Comment by wingkwong** [comment]
Couldn't reproduce now. It seems it has been fixed.

Tested Env:

Node: **v14.18.0**
Arch: **x64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.84.6**
