### ISSUE TITLE
🐛 Bug: Attachment Display & Download Issue on SSL Fresh Installation

### ISSUE THREAD

**Issue by kslaggs** [nocodb/nocodb#9786]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

1. Begin with fresh/clean installation of Ubuntu 24.10 as DigitalOcean droplet
2. Configure data.mydomain.com domain in Ubuntu (edit /etc/hostname, /etc/resolv.conf, and /etc/hosts files appropriately)
3. Install NocoDB using Auto-Upstall (bash <(curl -sSL http://install.nocodb.com/noco.sh) <(mktemp))
4. Select Y for SSL installation.  Domain data.mydomain.com
5. Installation completes
6. Access NocoDB at https://data.mydomain.com
7. Set up super admin account
8. Create base with attachment column. 
9. Attach image to record (jpg in this example)
10. Attachment thumbnail/preview generation does not work. Generic icon displayed instead. 
11. Clicking on the attachment does not generate a preview. Dark gray overlay screen is still shown. 
12. Downloading the attachment using the download button results in interrupted download and security warning about download being delivered over HTTP connection.  (In Firefox).

Note that this issue only presents in installations with SSL option enabled.  Installations that select "N" (no) SSL in my environment result in normal / expected attachment behavior with normal preview, thumbnail, and download behavior. 

### Desired Behavior

Fresh installation with SSL enabled should result in normal attachment behavior and generate previews / thumbnails correctly. Downloads should not be flagged by browser as potentially unsafe. 

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.257.2**

I have tried several times to install NocoDB using the auto-upstall method on a fresh Digital Ocean droplet running Ubuntu 24.10 and every attempt has resulted in attachment columns not working correctly. 

When installing NocoDB with SSL enabled, attachment previews for images (JPG, PNG etc) and downloads in the attachment column appear to be broken.  When attaching an image, a generic icon is displayed rather than a thumbnail of the image. Gallery view also does not show the attachment as a cover image. 

![Screenshot 2024-11-09 10123423336](https://github.com/user-attachments/assets/4fc351c6-39a5-4911-93ae-c67e287429ef)
![Screenshot 2024-11-09 134501551](https://github.com/user-attachments/assets/744ed7fb-761c-49c6-b7b7-6879a75a8c7e)

Attempting to download the file results in a security warning and blocked download with a warning about downloading over HTTP vs HTTPS. 

![Screenshot 2024-11-09 100523412](https://github.com/user-attachments/assets/3871152d-1cf7-407b-8100-4cac9da9bdf6)

I have seen a similar issue reported and there was a suggestion to add the environment variable "NC_PUBLIC_URL" with my public URL.  I have tried this with no success using https://data.mydomain.com as my environment variable.   I am a beginner and I am editing my environment variables in ~/nocodb/docker.env

![Screenshot 2024-11-09 1046541948](https://github.com/user-attachments/assets/3af82af6-e71d-4af4-a39f-2af5155b4e26)

I do not know if this is a bug or a configuration issue that is not in the installation documentation. 

### Attachments

![Screenshot 2024-11-09 134501551](https://github.com/user-attachments/assets/86527429-73c2-4c54-9d0d-b96140f78e25)
![Screenshot 2024-11-09 1046541948](https://github.com/user-attachments/assets/638b76ac-aef6-4d11-ab5b-9a86e46076ac)
![Screenshot 2024-11-09 10123423336](https://github.com/user-attachments/assets/1a16383c-0e5a-49b8-948f-f376903300d7)
![Screenshot 2024-11-09 102342341636](https://github.com/user-attachments/assets/64b0e1bf-bdfb-4402-b5b5-51ec1a473d6b)
![Screenshot 2024-11-09 100523412](https://github.com/user-attachments/assets/bc235a1c-adbb-40b5-8ef6-f01d3d9b82db)

**Comment by DarkPhoenix2704** [comment]
> Attempting to download the file results in a security warning and blocked download with a warning about downloading over HTTP vs HTTPS.



Does clicking "Allow download" downloads the file?

**Comment by kslaggs** [comment]
Yes, the file downloads successfully by bypassing the security warning and clicking "allow download".

**Comment by DarkPhoenix2704** [comment]
It looks like this is a Content Security Policy (CSP) issue. Your browser is blocking the download because it's coming from an unsecured HTTP connection while your main site is on HTTPS.

As a workaround, I recommend setting up SSL/HTTPS for your MinIO server as well. This will resolve the mixed content warning and ensure all communications are secure.

**Comment by kslaggs** [comment]
Thank you for looking into this. I agree with your logic. 

Regarding the suggested workaround, are you saying that I should switch to MinIO for local stroage? 

I'd like to solve it, if possible, but I am lacking experience.  As far as I can see, I am not using a MinIO server for storage. I am using S3 (local). This was set up by default during installation.  I did not make any of the storage choices and I am using default settings as defined nocoDB's auto-upstall script <(curl -sSL http://install.nocodb.com/noco.sh) <(mktemp))

![Screenshot 2024-11-10 202723441](https://github.com/user-attachments/assets/9033703c-ee8e-4490-948f-27f33cca10be)

![Screenshot 2024-11-10 20234232811](https://github.com/user-attachments/assets/1db63294-b8d0-470f-bebd-d9cc1e1d086f)

I have also tried using **https://my-public-ip:9000** as the S3 endpoint and that results in an error and breaks attachments altogether. 

If you could point me in the right direction I would appreciate it.

**Comment by kslaggs** [comment]
Sorry for my confusion. I see now that minio is the storage solution.  

Unfortunately, I do not know how to configure for SSL/https.

**Comment by DarkPhoenix2704** [comment]
If you're starting fresh without any existing data, here's a simple solution:

1. Launch a new droplet
2. Run the AutoUpstall script
4. When prompted, select "Advanced Options"
5. You'll be asked for:
   - Minio Domain Name (enter your domain)
   - SSL configuration (enter y)
   - For other options, you can simply press Enter to skip

This will set up everything with SSL properly configured from the start, which should resolve the download security warning.

Let me know if you need any help with this process!

**Comment by kslaggs** [comment]
Thanks for your help.  Still having issues. 

As a test, I have reinstalled nocoDB using advanced options, which asks about SSL for minio. Thank you for that pointer. 

Using SSL for minio is creating self-sign certificate errors in both accessing the site at my public domain, and also a 400 error when trying to attach files in a table.  

![Screenshot 2024-11-10 2143453737](https://github.com/user-attachments/assets/0a227ec7-3684-4150-b95f-03d27c8aea24)

![Screenshot 2024-11-10 2234213567422](https://github.com/user-attachments/assets/92a68739-c7f2-4462-a654-c48054319a2a)
![Screenshot 2024-11-10 20234232811](https://github.com/user-attachments/assets/834292b7-3abe-4f99-bec7-48313a400919)

**Comment by DarkPhoenix2704** [comment]
To fix the SSL issues, please follow these steps:

1. Run the AutoUpstall Command again
2. When asked "Do you want to reinstall NocoDB?" 
  - Just press Enter to skip this step
3. You'll see the Management Menu
4. Press 4 and Enter to restart all docker containers

The SSL issues should be resolved automatically after a few minutes once the containers restart.

**Comment by DarkPhoenix2704** [comment]
For Context, user has configured SSL for the NocoDB, but not for the Minio. This was causing [CSP Issue](https://github.com/nocodb/nocodb/issues/9786#issuecomment-2467189964).  This can be resolved by setting SSL for the [Minio also](https://github.com/nocodb/nocodb/issues/9786#issuecomment-2467287699). 



Second, user was facing SSL Errors. It was because, Traefik was already running when user configured the domain. Traefik attempted to verify the domain ownership and generate SSL certificates during its initial startup, but since the domain wasn't configured at that time, the verification failed. This can be resolved by restarting [traefik container. ](https://github.com/nocodb/nocodb/issues/9786#issuecomment-2467352769)

**Comment by kslaggs** [comment]
Thanks. I appreciate your continue support. 

Restarting container restored access to the site using SSL / https. 

However, there is still an attachment issue.  

As before, when attempting to upload an attachment in the attachment column, I get "Request failed with status code 400" and the attachment fails. 

When I investigate S3 in storage settings and click 'test',  I get "self-signed certificate" pop-up error.

**Comment by DarkPhoenix2704** [comment]
Hey, I need more info. Can you connect me on Discord?. My Discord ID is `darkphoenix2704`

**Comment by kslaggs** [comment]
> Hey, I need more info. Can you connect me on Discord?. My Discord ID is `darkphoenix2704`

Yes, thank you. I have sent you a friend request from 'numbre002'.

**Comment by joshbrake** [comment]
I'm also experiencing this issue and would be curious to hear what the resolution is. I can see the uploaded files in the Minio data folder, but previews from the database view are broken. I have existing data and so I did not want to go the fresh install route.

**Comment by kslaggs** [comment]
I was unable to solve and ended up going with paid S3 storage, which works fine with self-hosting.

**Comment by DarkPhoenix2704** [comment]
Hi @joshbrake 


Have you configured SSL for NocoDB & Minio?

**Comment by joshbrake** [comment]
@kslaggs Yes, I ended up adding S3 storage as well which works out of the box without issue.

**Comment by joshbrake** [comment]
@DarkPhoenix2704 yes, I did configure SSL for NocoDB. I tried to do the same for Minio, but I must have been doing something incorrectly inside the container. I looked in the Minio docs and copied in the SSL certs from the letsencrypt files for the NocoDB SSL certs but was still getting SSL errors when trying to preview files in the NocoDB fields.

**Comment by wrb2012** [comment]
I think traefik enabled by auto-upstall didn't respect my custom port. When I use  docker install(with ` -e NC_PUBLIC_URL="https://db.domain.com:8996"`) and nginx, image cover are OK.

**Comment by DarkPhoenix2704** [comment]
We have patched the AutoUpstall script to fix the ssl related issues and provide proper warning to users in all installation cases.
