### ISSUE TITLE
🐛 Bug: adding a new mysql data source requires db user with `create database` permission

### ISSUE THREAD

**Issue by farzadpanahi** [nocodb/nocodb#9990]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

1. create a mysql connection/integration using a db user with no `create database` permission
2. try to create a new data source using this connection to connection to an *existing* database
3. you will get the following error:
```sql
create database if not exists `blah_blah_db` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci - Access denied for user 'user_no_db_create_access'@'%' to database 'blah_blah_db'

```

### Desired Behavior

we should be able to use a user with no `create database` permission to access an existing database in mysql.
more specifically, I think this sql command `create database if not exists` should not be used. instead we should check for db existence with a different command first and if it does not exist then call `create database`.

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.258.3**

**Comment by maximejobin** [comment]
NocoDB cannot be used because of this major issue.

When connecting to an external database, why would you try to create it? I truly doubt there is a good reason for this. The "Connection to an external database" should only "connect" and not "create".

I hope this can be solved fast as there is nothing we can do until this is fixed... :'(

**Comment by maximejobin** [comment]
I updated to 0.260.2 and I still have the same message.

![image](https://github.com/user-attachments/assets/51d5d18b-b1f9-4df9-99dd-b6ad1c99ef18)

Do I need to do something except updating the app? I ran `./update.sh`.

**Comment by mertmit** [comment]
Hi @maximejobin 
We are using `packages/nocodb/src/db/sql-migrator/lib/KnexMigratorv2.ts` file to trigger initial meta sync.
I added a check before creating db which will skip that call if the database exists.
I confirmed it is avoiding that call on my setup as well.

Please confirm your version by hovering the NocoDB logo:
<img width="161" alt="image" src="https://github.com/user-attachments/assets/7463ddce-b0cb-41be-9fab-9ef6d9426eea" />

Also please make sure your user is configured properly for remote connections as your error consist of access denied to database, easiest way would be trying to connect to that database using your user with cli to confirm.

If it still persist can you please share following:

- Are you using MySQL or MariaDB & which version?
- What are the privileges of the user you've created (creation sql would be excellent)

**Comment by maximejobin** [comment]
Hello @mertmit,

Thank you for the answer.

I confirm I have the right version:
![image](https://github.com/user-attachments/assets/8ae64e3f-ef12-419b-8813-8ed29d265c78)

When I go to "Integrations", select "MySQL", enter all the credentials and click on Test Connection, I get this:
![image](https://github.com/user-attachments/assets/b8f98258-632c-479e-9f57-b2c79b636bea)

Then, I go in a base, click on "Connect External Data", enter a "Data Source Name", select my connection, enter the "Database" and click on "Test connection", I get this:
![image](https://github.com/user-attachments/assets/e6013381-9cde-46be-b185-291b849418fc)

Then when I click on "Add Source", I get this:
![image](https://github.com/user-attachments/assets/fa2afb55-aa18-4844-8105-8d429dcf9789)

I guess the bug wasn't clear enough (my bad!). The problem is not to ADD an integration (which worked and still works). The problem is not when we "Test connection". The problem is when we click on "Add Source" from a connection I just created.

I hope we gave you more/enough information to understand and fix the issue!

Let me know if you can reproduce the issue.

**Comment by maximejobin** [comment]
I did not answer your questions... so here it is:

> Are you using MySQL or MariaDB & which version?

MySQL 8 (Managed database from DigitalOcean)

> What are the privileges of the user you've created (creation sql would be excellent)

Running `SHOW GRANTS for XXXX;` gives this:

    GRANT USAGE ON *.* TO "XXXX"@"%"
    GRANT SELECT, SHOW VIEW ON "database".* TO "XXXX"@"%"

The nocodb connection should only be able to view data and not edit anything.

I hope this helps!

**Comment by mertmit** [comment]
Thanks for the information, I to reproduce same on my end by creating an account with following:

```
CREATE USER 'mert'@'%' IDENTIFIED BY 'password';
GRANT USAGE ON *.* TO 'mert'@'%';
GRANT SELECT, SHOW VIEW ON deneme.* TO 'mert'@'%';
```

I also use MySQL 8(.4.2)

<img width="386" alt="image" src="https://github.com/user-attachments/assets/8ae9df4a-9953-41d9-80eb-b056402a9c46" />

It worked without calling the CREATE DATABASE query (I confirmed by adding debug logs).

<img width="1244" alt="image" src="https://github.com/user-attachments/assets/1db4c1b9-237f-47ca-bbb8-62d93cacef5c" />
<img width="1259" alt="image" src="https://github.com/user-attachments/assets/66ff5625-d1b3-42d2-8b11-8c2c04b4fe3b" />
<img width="288" alt="image" src="https://github.com/user-attachments/assets/dcf79e6d-e048-4166-bbab-40ac848805e0" />


In your case it seems `SHOW DATABASES LIKE 'dbname'` query fails so your instance falls back to try creating the database. 

Can you please confirm if your account is not restricted to a specific host using following query:

```
SELECT User, Host FROM mysql.user WHERE User = 'XXXX';
```

Also if possible please confirm your account can run following query & get your database as result (with workbench, table plus or any other tool):
```
SHOW DATABASES LIKE 'dbname'
```

Even with your privileges you should be able to see the database you've granted some permissions (I have many other db but I can only see trial db I've setup):
<img width="431" alt="image" src="https://github.com/user-attachments/assets/04531d91-d9d0-4b1e-b394-a3552ba139d3" />

**Comment by maximejobin** [comment]
The following commands work perfectly:

    SHOW DATABASES;
    SHOW DATABASES LIKE 'dbname'; // with the right name

But this command fails:

    SELECT User, Host FROM mysql.user WHERE User = 'XXXX';

...with the error : 

    SELECT command denied to user 'XXXX'@'1.2.3.4' for table 'user'

Let me know if that helps or if you need more infos!

**Comment by mertmit** [comment]
Hey just to clarify that please run last command in an admin account if possible just to confirm your account is allowed to connect from your server where NocoDB instance hosted.
Other option is creating a new account with sometempname@'%' and retrying.
Sorry for the inconvenience you are having but still I am not able to reproduce, so please make sure your instance is allowed to connect mysql server. Meanwhile I will test a few other scenario and keep you updated.

**Comment by maximejobin** [comment]
I can run the last command as an admin successfully : 

    SELECT User, Host FROM mysql.user WHERE User = 'XXXX';

> Sorry for the inconvenience you are having but still I am not able to reproduce, so please make sure your instance is allowed to connect mysql server. Meanwhile I will test a few other scenario and keep you updated.

Don't worry! You are responsive and I know you are doing your best to help. I do not want to derail you... but when I want to "Connect to an external database", it seems obvious to me that the DB exists. I just don't understand in what scenario it would make sense for you to try to create the database.

I have **never** used a web application that creates the database itself. It can create tables, for instance, but the database? Never. Why are you trying to do that?

**Comment by mertmit** [comment]
Please confirm result of that query includes a proper user configuration ('XXXX' with server you are hosting NocoDB as Host - feel free to share by hiding your information).

The choice to create a remote DB if it does not exist was likely made in the very early days. To maintain backward compatibility I implemented a hybrid approach: it first tries running `hasDatabase` (wrapper around db specific query), and only if the `hasDatabase` query fails does it fall back to creating the database.

On the other hand even if we deprecate that behavior your issue would still remain as `hasDatabase` query run from NocoDB instance seem to fail.

See for instance when I enable debug logs for knex it doesn't trigger create db call as long as db exists:

<img width="418" alt="Image" src="https://github.com/user-attachments/assets/2401b673-8e84-46bd-9bb8-e887c43de025" />

And it fails if I try a db that doesn't exist (or non-authorized):

<img width="1055" alt="Image" src="https://github.com/user-attachments/assets/7ec4fb06-4425-450f-8262-27718f7f281c" />

Can you please check your server logs and share? (only related logs would be enough)

**Comment by maximejobin** [comment]
Sorry for the delay.

I confirm the credentials are permissions are good.

I can connect using the user and browse the tables exactly as I expect. Adding the same information in Nocodb works when I "Test connection" but NOT when I click "Add Source".

As the "Test connection" works, what's the point of such button if testing is not a proof that adding the source will work. Also, I think you should give a better feedback when it does not work. Printing the query that did not work does not help in the resolution because there could be multiple reasons for the failure. More checks should be added to know exactly why it is not working.

In my specific use case, I need to connect to an external database that is used by another software (WordPress, in this specific use case). The data or the schema cannot be edited in any way, shape or form. That is why my nocodb user can only SELECT.

**Question: What are the steps to produce the logs you need? I'm sorry but I don't know how knex works exactly.**

I hope this helps!

**Comment by maximejobin** [comment]
I just created a new Nocodb instance and this bug isn't fixed.

**Comment by jcvanhalle-ec** [comment]
I had the same problem for a while (see workaroud below). 

But I upgraded a nocodb instance (pre bugfix) to NocoDB v0.262.5 and now a user with read-only capabilities can be used to retrieve data. It was already setup so in case I was missing something I created a nocodb-ro user in another mysql instance, granted this user read only capabilities to a wordpress database/schema and it seems to work, I can retrieve data:

![Image](https://github.com/user-attachments/assets/3eb1add1-f3a5-4aa4-b74c-7e4572399c79)

Since the source and database setup and test went smoothly I didn't dig the logs.

> In my specific use case, I need to connect to an external database that is used by another software (WordPress, in this specific use case). The data or the schema cannot be edited in any way, shape or form. That is why my nocodb user can only SELECT.

Are you me ? A work-around I used was to create a different mysql database then create views for needed tables and then create a user who can only read those views. It may not work for your use-case though, I only needed to access specific tables.

**Comment by maximejobin** [comment]
The workaround I found was to create a connection using a user with full rights. Then, I changed the credentials for the other user.

My use case is similar to yours : the user must never edit the data or structure. Creating views might be an option here.

I hope they reopen and fix this issue. @mertmit
